name: html_pdf_widgets
description: Convert html text to pdf widgets.
version: 0.0.5
homepage: https://github.com/n3o2k7i8ch5/htmltopdfwidgets

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pdf: ">=3.11.1 <4.0.0"
  html: ">=0.15.4 <1.0.0"
  http: ">=1.2.2 <2.0.0"
  printing: ">=5.9.1 <6.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.1.0
  test: ">=1.16.0 <2.0.0"